-- AlterTable
ALTER TABLE "PayrollRecord" ADD COLUMN     "attritionRiskScore" DOUBLE PRECISION,
ADD COLUMN     "dateOfBirth" TEXT,
ADD COLUMN     "earnedLeaveBalance" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "employmentType" TEXT,
ADD COLUMN     "esicApplicable" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "financialStressIndex" DOUBLE PRECISION,
ADD COLUMN     "gender" TEXT,
ADD COLUMN     "gratuityEligible" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "gratuityProvision" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "groupHealthPremium" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "hiringSource" TEXT,
ADD COLUMN     "investmentDecl" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "lastIncrementDate" TEXT,
ADD COLUMN     "lastIncrementPct" DOUBLE PRECISION,
ADD COLUMN     "lateOrEarlyCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "leavesThisMonth" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "offerCtc" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "payslipDelivered" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "perfRatingCurrent" TEXT,
ADD COLUMN     "perfRatingPrevious" TEXT,
ADD COLUMN     "probationEndDate" TEXT,
ADD COLUMN     "projectedAnnualTax" DOUBLE PRECISION,
ADD COLUMN     "promotionCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "reportingManagerId" TEXT,
ADD COLUMN     "salaryCompressionRatio" DOUBLE PRECISION,
ADD COLUMN     "taxRegime" TEXT,
ADD COLUMN     "trainingCostAmort" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "variablePayoutPct" DOUBLE PRECISION,
ADD COLUMN     "variableTargetPct" DOUBLE PRECISION,
ADD COLUMN     "wfhDays" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "workLocation" TEXT;
